### ISSUE TITLE
Onboarding needs a non github page

### ISSUE THREAD

**Issue by karthik** [ropensci/software-review-meta#16]
a regular web page that explains why this exists, the motivation etc. Should be aliased to http://onboarding.ropensci.org/

**Comment by maelle** [comment]
Could be a very simple md page below content/ to begin with. It'd align with the style of the rest of the website.

**Comment by maelle** [comment]
note that ropensci.org/onboarding points to the volunteering form, which might be confusing

**Comment by maelle** [comment]
https://ropensci.org/software-review/ is up
