### ISSUE TITLE
ROpenSci Helper Package

### ISSUE THREAD

**Issue by noamross** [ropensci/software-review-meta#2]
Things it might do:

-  Run goodpractice with custom checks
-  Generate README template, lines for readme badges
-  Populate collaborators section of README
-  Automate CITATION file creation
-  Submit package?
    -  Wrap a tool for submitting to Zenodo, too.
-  Pull ROpenSci package data from API

**Comment by noamross** [comment]
-  Generate citations of package dependencies for JOSS `paper.md`

**Comment by sckott** [comment]
prior art, some related and some less related, but including in case of interest:

* https://github.com/ropensci/ro
* https://github.com/ropensci/ropkgs
* https://github.com/ropensci/ropensciToolkit

**Comment by maelle** [comment]
Linked to https://github.com/ropensci/onboarding-meta/issues/18

**Comment by maelle** [comment]
What does "Populate collaborators section of README" mean @noamross ?

**Comment by noamross** [comment]
I...do not remember.

**Comment by maelle** [comment]
Ah too bad! What about "Pull ROpenSci package data from API"? The rest is covered by usethis (README template) / issues in rodev.
