### ISSUE TITLE
wishlist: goodpractice::gp as an opencpu endpoint

### ISSUE THREAD

**Issue by karthik** [ropensci/software-review-meta#23]
Goodpractice doesn't always work on my machine and I have to ssh into another box to get it running. I also have to clone the latest version of a submitted package and then run good practice on it. A solution to make it easier for authors and editors to run this (no matter where they are, on a laptop/phone etc)

- First, a simple and thin wrapper around goodpractice that takes a `gh_user/repo` as input and then clones, runs goodpractice, and then returns the output (and also writes it to a text file with `hash.txt`)

- When someone tries to run gp again on the same version of the package, the hash check just returns output from the cached file. Otherwise it runs again.

- The URL (e.g. `onboarding.ropensci.org/gp/karthik/r-package`) could even be templated into the first editor response and the author/reviewer can reload as many times as needed through the process.

- In a fancy future where we have a bot, it can just monitor new commits on the repo and report changes in gp to the issue but that just a pie in the sky future.

**Comment by maelle** [comment]
I think this could be closed and discussed inhttps://github.com/ropensci/gpapi?

**Comment by maelle** [comment]
https://github.com/sckott/foobar3

**Comment by maelle** [comment]
related to work by @mpadge

**Comment by mpadge** [comment]
Documenting here a current endpoint that delivers it, to highlight the non-trivial nature of this, because that package is entirely designed around a single `print` method which itself relies entirely on `cli`, therefore ascii-format strings, and so can not be delivered to an enpoint. The current version extracts most of the info used to populate that `print` method.

``` r
library (httr)
library (magrittr)
port <- 22051
u <- "https://github.com/hypertidy/geodist"

system.time (
x <- sprintf ("http://<our/current/url>:%s/gp?u=%s", as.integer (port), u) %>%
    httr::POST () %>%
    httr::content () %>%
    unlist () %>%
    jsonlite::fromJSON ()
)
#>    user  system elapsed 
#>   0.037   0.010  64.130
print (x)
#> $covr
#>  [1] "geodist Coverage: 91.91%"        "src/geodesic.c: 74.96%"         
#>  [3] "R/utils.R: 97.37%"               "src/dists_xy_vec.c: 99.04%"     
#>  [5] "R/geodist-vec.R: 100.00%"        "R/geodist.R: 100.00%"           
#>  [7] "R/georange.R: 100.00%"           "src/common.c: 100.00%"          
#>  [9] "src/dists_paired_vec.c: 100.00%" "src/dists_paired.c: 100.00%"    
#> [11] "src/dists_seq_vec.c: 100.00%"    "src/dists_seq.c: 100.00%"       
#> [13] "src/dists_x_vec.c: 100.00%"      "src/dists_x.c: 100.00%"         
#> [15] "src/dists_xy.c: 100.00%"         "src/geodist_init.c: 100.00%"    
#> [17] "src/range_seq.c: 100.00%"        "src/range_x.c: 100.00%"         
#> [19] "src/range_xy.c: 100.00%"        
#> 
#> $cyclocomp
#>                  name cyclocomp
#> 1             geodist         7
#> 2    check_vec_inputs         6
#> 3         geodist_vec         6
#> 4         geodist_seq         5
#> 5     geodist_seq_vec         5
#> 6          geodist_xy         5
#> 7      geodist_xy_vec         5
#> 8         georange_xy         5
#> 9   convert_to_matrix         4
#> 10       find_xy_cols         4
#> 11     geodist_paired         4
#> 12 geodist_paired_vec         4
#> 13          geodist_x         4
#> 14      geodist_x_vec         4
#> 15           georange         4
#> 16       georange_seq         4
#> 17         georange_x         4
#> 18   match_xy_pattern         4
#> 19  geodist_benchmark         3
#> 20        check_max_d         2
#> 
#> $lint
#>                             file line    type
#> 1               tests/testthat.R    1 warning
#> 2               tests/testthat.R    2 warning
#> 3  tests/testthat/test-geodist.R   40   style
#> 4 tests/testthat/test-georange.R   68   style
#>                                           message
#> 1 Avoid library() and require() calls in packages
#> 2 Avoid library() and require() calls in packages
#> 3 Avoid trailing semicolons, they are not needed.
#> 4 Avoid trailing semicolons, they are not needed.
```

<sup>Created on 2021-03-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
