### ISSUE TITLE
A simple R package for editorial work

### ISSUE THREAD

**Issue by karthik** [ropensci/software-review-meta#24]
The package polls this repo for issues, updates on issues, the airtables (list of reviewers and past reviews) and provides the following functionality:

`suggest_reviewers(topic_list)` - will return a tibble of potential reviewers with last review date, if they are currently in a review etc.
`submissions(outstanding = TRUE)` - any submissions that don't have editors or reviewers yet. `overdue = TRUE` will filter down to ones that have passed the 5 day turn around time.

`submissions(ongoing = TRUE)`
`reviewers()` full list with stats. `name = "foo"` returns history of that person.

This is just scraping the surface. A combination of these functions could be baked into a rmarkdown report that an editor could update daily to see what needs a nudge.

**Comment by maelle** [comment]
For the most part for this we will use Airtable itself.
