### ISSUE TITLE
ropensci/ropenscilabs transfer criteria

### ISSUE THREAD

**Issue by noamross** [ropensci/software-review-meta#37]
Which repo things live in came up again in: https://github.com/ropensci/zenodo/issues/20

Just a thought - how about our standard for things moving from ropenscilabs to ropensci, for staff-built packages that may or may not be reviewed, is that they have everything we would require for _submission_: roughly complete, with testing, CI, vignettes and docs?

I forget whether the current cleanup includes through staff repos in ropensci and decide whether they need to go to labs, and maybe also giving them repostatus badges.

**Comment by cboettig** [comment]
👍 for getting the appropriate repostatus.org badges on all repos in https://github.com/ropensci, and maybe also for those on https://github.com/ropenscilabs

**Comment by maelle** [comment]
have the badges been chosen btw? 😁

**Comment by sckott** [comment]
Yes! Repostatus

**Comment by maelle** [comment]
http://www.repostatus.org/ ?

**Comment by maelle** [comment]
(and thanks!)

**Comment by sckott** [comment]
yes, that one

**Comment by maelle** [comment]
@noamross the in-progress curation policy should help closing this :-)

**Comment by maelle** [comment]
curation policy now up

**Comment by maelle** [comment]
https://devguide.ropensci.org/curationpolicy.html
