### ISSUE TITLE
Generate package code statistics on submission

### ISSUE THREAD

**Issue by noamross** [ropensci/software-review-meta#42]
It would be useful to get package code statistics via `cloc` on submission.  A bonus would be if `cloc` could distinguish between raw comments (often indicators of "ghost code") and roxygen comments (which may indicate well-developed documentation).

**Comment by maelle** [comment]
- Using previous submissions/CRAN pkgs as comparison
- Also look at frequency of raw comments vs code (would show unreadable bc unexplained code?)
- Also generate statistics about no of exported classes&functions

**Comment by maelle** [comment]
We'd also need to decide what to do with the info. If a pkg is gigantic, suggest splitting +warn potential reviewers?

Oh and looking for code duplication cf https://github.com/MangoTheCat/goodpractice/issues/78

**Comment by maelle** [comment]
Does `launchboat` handle this @noamross ?

**Comment by noamross** [comment]
Yes, it has a `cloc` report, though `launchboat` needs some work.   Also I had discussed another idea for a package with Bob at the unconf, `cranstats`, that would hold pre-generated `cloc` and other data for all packages on CRAN, and then when run on a local package would show where it falls in the distribution.

**Comment by maelle** [comment]
Handled via pkgreport cc @mpadge
