### ISSUE TITLE
Tell people to change COC file name

### ISSUE THREAD

**Issue by sckott** [ropensci/software-review-meta#46]
only if it's `CONDUCT.md`, then change to `CODE_OF_CONDUCT.md` - i do realize `usethis` already has the latter, so all people using that will be fine

**Comment by maelle** [comment]
This should be a wave of PRs. 🤔

**Comment by maelle** [comment]
Maybe a tech note would help to increase awareness. 🤔

**Comment by sckott** [comment]
good idea

**Comment by maelle** [comment]
Or would it make sense to couple that with a blog post about the updates you and Stef made to the rOpenSci COC? 🤔

**Comment by stefaniebutland** [comment]
Code of conduct updates not finished yet but will be live in Dec. I guess we do need to put out a *short* post announcing that we've made updates, to name Committee etc, so could note this issue there

**Comment by maelle** [comment]
Duplicate of https://github.com/ropensci/dev_guide/issues/240
