### ISSUE TITLE
Recommend sf over sp?

### ISSUE THREAD

**Issue by maelle** [ropensci/software-review-meta#47]
@jhollist @ateucher @Robinlovelace @mpadge cc @sckott 

Dear geospatial+rOpenSci R people I can think of right now, do you think it would make sense for rOpenSci to recommend `sf` over `sp` in the onboarding guidelines?

[Here](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#tools) are our current package recommendations, e.g. xml2 over XML.

**Comment by Robinlovelace** [comment]
My 10 cents: yes!

**Comment by jhollist** [comment]
I agree with @Robinlovelace.  That being said some flexibility should be allowed given the state of flux with spatial, especially since `raster` doesn't yet fully support `sf` objects out of the box and requires coercing to `sp`.

**Comment by mpadge** [comment]
My :+1: to @jhollist 
```
recommend_sf <- FALSE
if (!"raster" %in% pkg.deps)
  recommend_sf <- TRUE

if (!recommend_sf){
  # be careful
}
```
That condition could be modified through extending @noamross's [`fasterize`](https://github.com/ecohealthalliance/fasterize)?

**Comment by maelle** [comment]
thanks for the feedbacl everyone! I forgot to tag @mdsumner 🤦‍♀️ @mdsumner, what's your opinion?

**Comment by ateucher** [comment]
I also agree it's best at this point to recommend `sf`, with the same caveats as @jhollist. There is a lot of the r world that is still firmly in the `sp/rgal/rgeos` ecosystem though. Lately I've been making `sf` the "first-class citizen" and include `sp` in `Suggests`, and support it by way of `sf`'s pretty great methods for coercion to/from.

**Comment by mpadge** [comment]
To complicate matters just a bit, there is the beastly nature of `sf` to consider. To borrow some [code](https://rud.is/b/2018/04/01/compute-visualize-drive-space-consumption-of-your-installed-r-packages/) from @hrbrmstr:
```{r}
library (fs)
library (tidyverse)
installed.packages() %>%
    as_data_frame() %>%
    mutate(pkg_dir = sprintf("%s/%s", LibPath, Package)) %>%
    select(Package, pkg_dir) %>%
    filter(Package %in% c ("sf", "sp")) %>%
    mutate(pkg_dir_size = map_dbl(pkg_dir, ~{
              fs::dir_info(.x, all=TRUE, recursive=TRUE) %>%
              summarise(tot_dir_size = sum(size)) %>% 
              pull(tot_dir_size)
    }) %>%
       format(big.mark = ",")) %>%
    select (Package, pkg_dir_size)
#  Package  pkg_dir_size
#  sf       18,902,203
#  sp       2,093,160
```
Recommending a package that is almost 10 times the size of its predecessor; that represents one of the largest installs in anybody's `site-library`; and that by my reckoning is close to 20GB, by @hrbrmstr's more like 113GB, would suggest something like:
```
if (recommend_sf){
  # be careful
}
```

**Comment by hrbrmstr** [comment]
ohai! 

(MB not GB :-)

I was _shocked_ when I saw the results of the lib dir sizes. 

There's also this to consider:

`sp` dep tree
![image](https://user-images.githubusercontent.com/509878/38767329-283c7270-3fad-11e8-9791-deaf651a1fe1.png)

vs 

`sf` dep tree
![image](https://user-images.githubusercontent.com/509878/38767339-4f610078-3fad-11e8-9d6d-f04224614bad.png)

`sf` brings a ton of heavy hitters along for the ride.

**Comment by maelle** [comment]
Thanks all! A lot of food for thought! 🤔 💥

**Comment by Robinlovelace** [comment]
Cannot compete with Bob's viz (awesome stuff - shows how interdependent we're all becoming which I recall you saying is a tendency to resist!) but just thought I'd flag that many of those pkgs will already be installed on many useRs computers, especially `magrittr + Rcpp` given their popularity. Not sure about `e1071` but I'd argue that uptake of `units` is no bad thing (notwithstanding its potentially painful dependency on the C library udunits2):

![image](https://user-images.githubusercontent.com/1825120/38767507-d4625916-3fda-11e8-98df-39c23f0bcc72.png)

Code: https://github.com/Robinlovelace/geocompr/blob/master/code/cranlogs.R but starting out with this:

```r
pkgs = c("Rcpp", "MASS", "e1071", "units", "magrittr")
dd = cranlogs::cran_downloads(packages = pkgs,
                              from = "2013-01-01", to = Sys.Date())
```

**Comment by cboettig** [comment]
Just wondering if it is worth re-framing the question somewhat: is there some approach that developers of packages working with spatial data (e.g., accessing a data repository or API that distributes spatial data) can do to make their packages more `sf`-ready?

Or more generally, would it make sense to have some recommendations about spatial data standards in rOpenSci not necessarily tied to any particular package ecosystem?  e.g. for starters, "packages working with spatial data should declare the projection used".  Would it make sense to suggest something like `geojson` as a preferred format for vector spatial data (unless the data needs one of those unusual simple features not part of the geojson standard?)  Or is that unnecessarily prescriptive (i.e. users are better off always firing up the `sf` / `libgdal` swiss-army knife and enjoy agnosticism to filetype?)

**Comment by mpadge** [comment]
For the same of completeness here, [here is a link to an issue thread](https://github.com/r-spatial/discuss/issues/48#issuecomment-798543339) where @edzer states:

> the maintainer of `sp` has made it clear that new software should build upon `sf`, not `sp`. There is no longer a reason to continue building new software using `sp` classes.

**Comment by edzer** [comment]
Now that @rsbivand has retired, `rgdal`, `maptools` and `rgeos` will retire as well, by the end of 2023. To do that, `sp` will have to depend on `sf`: right now `sp` uses `rgdal` and `rgeos` for important tasks (validation of CRS, hole-in-polygon detection, although `rgdal` and `rgeos` are "just" in `Suggests:`. `sp` is not the way forward.

**Comment by rsbivand** [comment]
Any role for a maintenance-mode only **sp** going forward is to keep packages using spatial vector representations and unwilling to migrate to **sf** directly from breaking. For similarly placed packages using S4 classes inheriting from **sp** gridded classes, the picture is more complex, as **stars** and **terra** are arguably both useful alternatives, and should both be supported, but with no recommended preference (use cases should decide for themselves). So for vector data, yes, only recommend **sf**; for raster data, probably no call should be made beyond pointing out that **raster**'s use of **rgdal** to access GDAL has EOL to the end of 2023 latest.

**Comment by mpadge** [comment]
Thanks @edzer and @rsbivand for useful clarification! We'll update our [recommended scaffolding section of our Development Guide](https://devguide.ropensci.org/building.html?q=scaffo#recommended-scaffolding) to restate what you've clarified here. Much appreciated, and all the best to you @rsbivand for your days and years ahead! The entire R community will long remain deeply indebted to your contributions!

**Comment by rsbivand** [comment]
Thanks @mpadge ! The proposed scaffolding text looks well-balanced.

**Comment by mpadge** [comment]
Ping our Associate Editor for Spatial Software, @Paula-Moraga, so you're aware of these updates :smile: Our automated checking system will notify whenever these (potentially) obsolete packages are used, so you'll see any such cases straight away.

**Comment by maelle** [comment]
Resolved by @mpadge's PR to the dev guide https://github.com/ropensci/dev_guide/pull/362

Thanks to all those who chimed in!
