### ISSUE TITLE
Build a new template for submission

### ISSUE THREAD

**Issue by karthik** [ropensci/software-review-meta#52]
This will work for:
- A web form
- Submission via YML
- Submission via R package (which will also parse YML if present).

Edit template here till we are happy with a version to work with: 

https://docs.google.com/document/d/1ej99Ku1qzQrH49sRM1t5wqeqa3cSENV9strEkVG-VQM/edit?usp=sharing

**Comment by karthik** [comment]
Referencing #51

**Comment by maelle** [comment]
Closing in favor of #51

**Comment by maelle** [comment]
But I am reading the Google Doc to extract ideas e.g. https://github.com/ropensci-org/buffy/issues/10
