### ISSUE TITLE
Standard testing environment

### ISSUE THREAD

**Issue by noamross** [ropensci/software-review-meta#54]
We should set up a docker image for a standard testing environment.  Our stack has a lot of system dependencies, so maybe we should use rocker/ropensci, with goodpractice installed.

**Comment by karthik** [comment]
Agreed. `goodpractice` does not work on my local environment so I already do this on a docker container. Would be nice for that to be a standard one we use that also contains the latest goodpractice.

**Comment by noamross** [comment]
Should this test against R-release or R-devel?  I guess ideally it should do both and report if there are differences, but for the first iteration?

**Comment by noamross** [comment]
Currently working on this over here: https://github.com/noamross/launchboat . Will try to have done before unconf and move it over to ropenscilabs.

**Comment by maelle** [comment]
Handled via pkgreport cc @mpadge
