### ISSUE TITLE
A more comprehensive rOpenSci directory

### ISSUE THREAD

**Issue by noamross** [ropensci/software-review-meta#6]
Despite our growing reviewer base, it can still be challenging to identify good package reviewers.  I was wondering whether it would be worthwhile to expand the reviewer's directory to an all-RO community directory, that would include everyone who has submitted a package, reviewed, attended (or applied) an unconf, interned, fellow'd, or otherwise participated in a significant way.  This may especially true because I think our more recent unconf base is more diverse than our historical reviewer base, so it would be good to have the larger set for assigning diverse reviewers. I'm not sure if @stefaniebutland already maintains something like this.

**Comment by cboettig** [comment]
Related: you might look at the list of authors on all rOpenSci packages, which is available in the codemeta corpus https://codemeta.github.io/codemetar/articles/codemeta-parsing.html

**Comment by noamross** [comment]
Cool, thanks! Yes, have been meaning at minimum to get package authors in our reviewer list.  Though actually our package authors are one of our less diverse subgroups - which speaks to our need to do more targeted author recruitment.

**Comment by sckott** [comment]
Do you mean a public one, or just a table in our Airtable for our use?

I maintain a directory in private repos as some details are sensitive, but could strip out details

**Comment by stefaniebutland** [comment]
I don't yet maintain a list of past unconf participants (or applicants) but @noamross you have access to 2017 info as member of selection committee. Let me know if you want explicit point to file

**Comment by noamross** [comment]
@sckott I guess this would be private for us to use as editors.

**Comment by stefaniebutland** [comment]
@noamross Revising my earlier curt answer. 
This aligns with my interest in "mapping the community" and my recent convos with @sckott and @karthik about community metrics and impact. 

We had agreed to start by making a list of everything about a "person" that we might want to know, and your practical need for package reviewers would use a subset of this info. (Companion list would be everything about a "product/packages" that we might want to know.)

I've made a first attempt at the "Person" list in a gdoc with links to some data @sckott has compiled and I'm putting it in our private comms repo but will share the link with you so you might indicate which fields are important to you.

**Comment by maelle** [comment]
Also linked to the discussion of volunteers/reviewers survey/form in a private repo.

**Comment by maelle** [comment]
Can this be closed? (the new reviewer form link, once the form is launched, will be given to authors by editors cf #43 )
