### ISSUE TITLE
Add text to package description in DESCRIPTION

### ISSUE THREAD

**Issue by maelle** [ropensci/software-review-meta#62]
The peer-reviewed package could have a sentence like "This package has been peer reviewed by rOpenSci (v. 2.3.0)." in DESCRIPTION. Point made by @noamross 

In practice, I'd write a helper function in `rodev` using `desc`.

**Comment by noamross** [comment]
If implemented, we should add this to the approved template: https://github.com/ropensci/dev_guide/blob/master/templates/approved.md

**Comment by maelle** [comment]
There is now a function in `rodev`

```r
# add rOpenSci peer-review (for onboarded packages)
add_ro_desc()
```

I won't add `rodev` to the guidance yet because it's not fully ready. Should the sentence for DESCRIPTION go in the template before I "release" `rodev` @noamross ?
