### ISSUE TITLE
using covrpage to communicate between reviewers and devs

### ISSUE THREAD

**Issue by yonicd** [ropensci/software-review-meta#63]
continuation of thread started [here](https://twitter.com/yoniceedee/status/1047895156949745670). 

[covrpage](https://github.com/yonicd/covrpage) gives the package developer a simple tool to disseminate to potential users and collaborators the depth of unit testing and code coverage. Conversely, the users and collaborators can reliably verify that the developer has done due their diligence in the unit testing. 

This goal is achieved by embedding the results from {covr} and {testhat} in human-readable markdown/html document containing summary tables that supply the reader links to drill into the details of testing and code coverage.  

Paired with continuous integration the readme is generated independently of user interaction.

Hopefully this tool can be used by ropensci reviewers to communicate more effectively among each other and to the developers current package test/coverage status and what still needs to be worked on. And more importantly a method for end users to quickly understand what are the weak points of a package they are thinking of using.

**Comment by maelle** [comment]
Thanks @yonicd! 

My opinion: I wouldn't like to have such a detailed report in the README but I can imagine it being useful for reviewers, although I still need to think (and give it a try hopefully soon!).

**Comment by yonicd** [comment]
Thanks! Btw it is the tests dir readme not the root directory readme.

**Comment by maelle** [comment]
Aaah makes sense!!

**Comment by yonicd** [comment]
the conversation with jim on the testing has been really informative for my understanding of careful testing communication.

I get the feeling that as new developers are maturing the initial inteded use of testing/coverage stats is evovling to meet broader needs.

**Comment by yonicd** [comment]
i updated the output to make the non-passing lines pop out more, and give a disclaimer regarding what jim was getting at in the coverage stats. 

[example site](https://github.com/yonicd/ggstatsplot/tree/master/tests)

![screen shot 2018-10-08 at 3 33 55 pm](https://user-images.githubusercontent.com/1755487/46631741-4872c400-cb16-11e8-996b-bfb5cdc7399c.png)
![screen shot 2018-10-08 at 3 34 09 pm](https://user-images.githubusercontent.com/1755487/46631745-4a3c8780-cb16-11e8-999e-6a01d7409b6d.png)
![screen shot 2018-10-08 at 3 34 18 pm](https://user-images.githubusercontent.com/1755487/46631747-4c064b00-cb16-11e8-86a6-aa485fc275cd.png)

**Comment by yonicd** [comment]
@maelle have you had a chance to test drive the package. Thanks

**Comment by maelle** [comment]
No, not yet! Will try to do it soon! 🤞  😿

**Comment by maelle** [comment]
Note to self: also try `covrpage::covrpage_snapshot()`.

**Comment by yonicd** [comment]
that function is being orphaned. it got too complicated to run once i moved from `testthat::test_dir` to `testthat:test_check`. you would need to install the whole package and it's dependencies for it to run. I didn't think it was useful at that point. 

user can just clone repo of interest and run `covrpage` instead.

**Comment by yonicd** [comment]
some things you can try in [HIBPwned](https://github.com/lockedata/HIBPwned) that will give a good idea of what the package can do to help communicate tests/coverage:

  - adding a [badge](https://yonicd.github.io/covrpage/articles/Test_Results.html#badge) to the main readme.md

  - create covrpage [vignette](https://yonicd.github.io/covrpage/reference/covrpage.html)

  - run in [ci](https://yonicd.github.io/covrpage/articles/Continuous_Integration.html#deploy-pkgdown)

**Comment by maelle** [comment]
Running it in CI means you effectively run the tests twice, right? And with a vignette, three times?
