### ISSUE TITLE
use a "discuss" badge pointing to the forum?

### ISSUE THREAD

**Issue by maelle** [ropensci/software-review-meta#64]
I.e. something like

[![Discourse forum](https://img.shields.io/badge/discourse-discuss-blue.svg?logo=comments&longCache=true)](https://discuss.ropensci.org/)

```
[![Discourse status](https://img.shields.io/badge/discourse-discuss-blue.svg?logo=comments&longCache=true)](https://discuss.ropensci.org/)
```

It might help attract people to the forum? Cons: one more badge; potentially misleading (forum vs issue tracker)

**Comment by sckott** [comment]
in readme of each repo?

**Comment by maelle** [comment]
Yes hence the cons, really not sure if it's a good idea.

**Comment by noamross** [comment]
I'm loathe to add more badges. An alternative option: We could re-do the RO footer so that it is actually a few images side-by-side with different links, one of which being the forum.

**Comment by maelle** [comment]
I like that idea! 😀

**Comment by karthik** [comment]
Im totally on the fence about this. Even as a person who is quite familiar with this project, I would be confused as to where I need to post my question (issue versus discourse). We may have to include on a guide on where to post based on the nature of the issue/question. Also agree with Noam that the badges have become unbearable flair at this point. 

![](https://media.giphy.com/media/ZMvG5L7Di4AgM/giphy.gif)

**Comment by maelle** [comment]
Yes, I prefer Noam's idea to maybe reformat the footer as a list of images with direct links to stuff.

I will add more guidance about questions to the dev_guide contributing chapter.

**Comment by maelle** [comment]
We've added mention of the forum to the dev guide. 
We should probably make sure the .github templates are clear too. https://github.com/ropenscilabs/rodev/blob/master/inst/templates/CONTRIBUTING.md links to https://ropensci.github.io/dev_guide/contributingguide.html 

Is this enough?
