### ISSUE TITLE
Eventually recommend tic and travis?

### ISSUE THREAD

**Issue by maelle** [ropensci/software-review-meta#66]
instead of the usual travis.yml file. cc @karthik 

(not before both packages are on CRAN anyway)

**Comment by maelle** [comment]
@karthik any opinion? 😺

**Comment by karthik** [comment]
Yes eventually! But for now it is a definite hold since the final project is not signed off yet.

**Comment by maelle** [comment]
tic is mentioned in https://devguide.ropensci.org/ci.html
