### ISSUE TITLE
Change issue template to include pre-sub template

### ISSUE THREAD

**Issue by sckott** [ropensci/software-review-meta#67]
Many pre-sub inquiries fill out a full submission  

We agree that it's probably because our issue template simply has the full submission template in it https://github.com/ropensci/onboarding/blob/master/issue_template.md

I think maybe there is a way to have different issue templates for different things? Or am I imagining that?  

If not then we could just add the pre-sub template to the top of the issue template, and say remove one or the  other depending on what you're doing

**Comment by maelle** [comment]
Yes there is a way https://blog.github.com/2018-05-02-issue-template-improvements/

**Comment by sckott** [comment]
cool

**Comment by karthik** [comment]
These new github features are really good!

**Comment by maelle** [comment]
This was actually solved by @karthik a while ago, we have several issue templates now. :-)
