### ISSUE TITLE
List of elements to mention in a blog update about the system

### ISSUE THREAD

**Issue by maelle** [ropensci/software-review-meta#72]
Since the latest blog post https://ropensci.org/blog/2017/09/11/software-review-update/

# New standards

* Windows CI conditions https://ropensci.github.io/dev_guide/ci.html#whichci
* `codemetar` https://ropensci.github.io/dev_guide/building.html#creating-metadata-for-your-package (and reminded in https://ropensci.github.io/dev_guide/approvaltemplate.html)
* Recommend using a structure for the release notes, recommend NEWS.md not NEWS https://ropensci.github.io/dev_guide/releasing.html#news
* repostatus.org badges (but if no badge, for ropensci.org/badges we deduce a status from the GitHub organisation: concept if ropenscilabs, active otherwise) https://ropensci.github.io/dev_guide/building.html#readme
* Using `roxygen2` is now an explicit requirement. https://ropensci.github.io/dev_guide/building.html#documentation

The whole dev_guide third part is new guidance, but it's all more suggestions than requirements except for the code of conduct and contributing guidelines. https://ropensci.github.io/dev_guide/collaboration.html

**Comment by noamross** [comment]
Other points to hit:
- New editors Lincoln and Anna https://ropensci.org/blog/2018/06/22/new_editors/
- The dev guide in general!
- New issue templates https://github.com/ropensci/software-review/issues/new
- Onboarding --> Software Peer Review https://github.com/ropensci/software-review-meta/issues/11
- Badge versioning?

**Comment by maelle** [comment]
@noamross I was {--rude--}{++helpful++} and added links to your list to have them when writing the blog post. :-)

**Comment by noamross** [comment]
I edited your meta-comment :)

**Comment by maelle** [comment]
Started draft https://github.com/ropensci/roweb2/pull/412

**Comment by maelle** [comment]
Blog post published a while ago https://ropensci.org/blog/2019/02/01/software-review-news/
