### ISSUE TITLE
Keep public lists of reviewers up to date

### ISSUE THREAD

**Issue by maelle** [ropensci/software-review-meta#75]
Automate the knitting of the README of software-review via Travis.

For this and for dev_guide trigger one Travis build a day (Zapier? Other ideas @sckott ?)

**Comment by sckott** [comment]
i assume you mean the list here https://github.com/ropensci/software-review#reviewers ?

**Comment by sckott** [comment]
i thought github actions might be an option, but looks like I only have it in my personal acct, not in this org

**Comment by sckott** [comment]
maybe it can be done with tic?

**Comment by maelle** [comment]
Yes that list and the one in dev_guide.

I am not worried about making each Travis build update the list (it already happens in dev_guide, and yes with tic) but am wondering *how to trigger one Travis build a day*. You used to do that for packages right?

**Comment by sckott** [comment]
yes, that was a heroku ruby script though.

you can schedule travis to run on a cron job within the travis settings now, not sure if that will help

**Comment by maelle** [comment]
Oh right, actually I should have looked at Travis docs earlier, it could hardly be any easier these days... https://docs.travis-ci.com/user/cron-jobs/

Set up for dev_guide, I'll work on that for the software-review repo as well.

**Comment by maelle** [comment]
Set up for software-review as well now.
