### ISSUE TITLE
Add itdepends as part of a reviewer's report

### ISSUE THREAD

**Issue by noamross** [ropensci/software-review-meta#76]
https://github.com/jimhester/itdepends looks like it will be a useful tool for assessing package dependencies.  It would be a good part of a future workflow where editors and reviewers get an automated report on the the package.  (Along with other parts of currently stalled projects https://github.com/ropenscilabs/pkgreviewr and https://github.com/ropenscilabs/launchboat)

**Comment by noamross** [comment]
Oh, I meant https://github.com/ropenscilabs/pkginspector was stalled, not sure about **pkgreviewr**!

**Comment by maelle** [comment]
@mpadge is this of any interest for pkgreport?

**Comment by mpadge** [comment]
Nope. One missing aspect that `itdepends` was heading towards is a [dependency "footprint"](https://rud.is/b/2018/04/01/compute-visualize-drive-space-consumption-of-your-installed-r-packages/), but calculating that requires full installations of everything, which is definitely not worth doing just for one extra metric. As is, we now extract full info on all dependencies of every sort, and i think that suffices here.

**Comment by maelle** [comment]
@noamross still ok to close the issue or do we still want more dependency info at some point? Maybe we could just suggest using itdepends in the reviewer guide or so.
