### ISSUE TITLE
EiC history

### ISSUE THREAD

**Issue by maelle** [ropensci/software-review-meta#77]
@noamross it ended up being easier just relying on my memory and Slack searches :see_no_evil: 

month_start|month_end|eic_login
-- | -- | --
2017-06 | 2017-08 | maelle
2017-09 | 2017-12 | sckott
2018-01 | 2018-03 | karthik
2018-04 | 2018-07 | noamross
2018-08 | 2018-09 | maelle
2018-10 | 2019-02 | sckott
2019-03 | 2019-04 | melvidoni
2019-04 | now | noamross

**Comment by noamross** [comment]
This is now stored in the AirTable. We can put it in the dev guide when built if we want.

**Comment by maelle** [comment]
In the chapter for editors?

**Comment by maelle** [comment]
And thank you!!
