### ISSUE TITLE
Keep requiring footer?

### ISSUE THREAD

**Issue by maelle** [ropensci/software-review-meta#79]
The footer is useful in GitHub READMEs but it is also redundant in docs website, see e.g. https://docs.ropensci.org/ropenaq/

Once Jeroen's docs project is mature, do we want to keep requiring the README footer? @karthik

**Comment by noamross** [comment]
I think it would be fine to leave it off. 

A note on this is that between moving to the ropensci repo and the rodocs site, the RO branding can overwhelm people's attempts to associate their package with themselves and their own organization's work.  I, for instance, put an EcoHealth footer on READMEs in packages developed through work, and put the authors at the top of the README, and want to keep this after a package goes through peer-review.

**Comment by maelle** [comment]
But it's fine to have that footer + the rotemplate style, right? You could also [add EcoHealth Alliance as author with a logo](https://github.com/ropenscilabs/rodev/blob/master/_pkgdown.yml#L10), is it fine or would you need more?

**Comment by noamross** [comment]
Yes, I think that's fine.  If I think of some other option it would be good to have I'll open an issue in **rotemplate**.

**Comment by maelle** [comment]
Opinions @karthik @sckott?

**Comment by sckott** [comment]
dont' have a strong feeling on it

**Comment by maelle** [comment]
Re-upping this, @jeroen now adds the same footer as for the website for pkgdown websites so the footer is redundant.

In READMEs one could argue that there's the peer-review badge at the top. 

Related (would become useless) https://github.com/ropensci/roweb2/issues/451

**Comment by jeroen** [comment]
I think we could drop the banner, and instead ask to add `https://docs.ropensci.org/${pkg}` to the package description file and the github repo "homepage" (the url at the top of the github repo page next to the description).

**Comment by maelle** [comment]
btw in GitHub docs I was unable to find docs for that field! The best link I could come up with is https://stackoverflow.com/questions/7757751/how-do-you-change-a-repository-description-on-github

**Comment by maelle** [comment]
Any objection to dropping the banner/footer image @noamross @sckott @karthik?

**Comment by noamross** [comment]
Agreed, I think we should drop it.

**Comment by jeroen** [comment]
@maelle in the github api the field is called the repo "homepage": https://developer.github.com/v3/repos/

**Comment by maelle** [comment]
@jeroen I know, but when you edit it it's called website. :cry: And I don't see it e.g. in https://help.github.com/en/github/administering-a-repository

**Comment by maelle** [comment]
@karthik fine if we stop requiring the footer?

**Comment by karthik** [comment]
Yes I don't really care if it stays or goes.

**Comment by maelle** [comment]
cf also https://github.com/ropensci/rodev/commit/a4c5abe4e85b118036790e9ba7fbd61b891196b2
