### ISSUE TITLE
Rename / split up "reproducibility" category in Aims and Scope?

### ISSUE THREAD

**Issue by noamross** [ropensci/software-review-meta#81]
I have noticed that lots of submissions and pre-submissions check off the "reproducibility" category even when they don't match the description we have under it.  I think it's because pretty much everything we accept is about reproducibility, even though we have narrowed that topic to mean a few specific things.  Should we rename it or split it up into constituent parts? (In the Aims & Scope and on the submission template)

**Comment by karthik** [comment]
I vote split into constituent parts.

**Comment by noamross** [comment]
Currently: 

> **reproducibility**: Tools that facilitate reproducible research. This includes packages that facilitate use of version control, provenance tracking, automated testing of data inputs and statistical outputs, citation of software and scientific literature. It does not include general tools for literate programming (e.g., R markdown extensions not under the previous topics).

One way to split:

- **Version control**: tools that support the use of version control in scientific workflows
- **Data validation and testing**
- **Scientific workflow automation and testing**, including provenance tracking
- **Citation management and bibliometrics**

**Comment by maelle** [comment]
LGTM. Maybe add the word "provenance" somewhere?

**Comment by sckott** [comment]
LGTM

**Comment by annakrystalli** [comment]
LGTM too
