### ISSUE TITLE
Update Spanish translation of pre-submission inquiry

### ISSUE THREAD

**Issue by noamross** [ropensci/software-review-meta#87]
The pre-submission inquiry has been update to include statistical peer-review: https://github.com/ropensci/software-review/blob/master/.github/ISSUE_TEMPLATE/B-submit-a-presubmission-inquiry.md

Can we update the Spanish pre-submission inquiry to reflect this? Spanish statistical review is a to-do that I'll raise in another issue.

**Comment by maelle** [comment]
https://github.com/ropensci/software-review/pull/456
