### ISSUE TITLE
Move all peer-reviewed packages to ropensci from ropenscilabs

### ISSUE THREAD

**Issue by noamross** [ropensci/software-review-meta#9]
This could follow all of our badging. This will make a clearer distinction between the two orgs.  I'm fine with non-peer-reviewed but mature (say, CRAN-submitted) internal RO packages moving from labs to main as long as the badge (and maybe in the future, codemeta.json) distinguishes the two.

**Comment by maelle** [comment]
@sckott you had started doing this right? I vaguely remember transferring my own onboarded packages from ropenscilabs to ropensci. Happy to help.

**Comment by maelle** [comment]
In progress

- [x] https://github.com/ropenscilabs/gutenbergr/issues/18
- [x] https://github.com/ropenscilabs/rnaturalearth/issues/20
- [x] https://github.com/ropenscilabs/camsRad/issues/6
- [x] https://github.com/ropensci/robotstxt/issues/25
- [x] https://github.com/ropensci/nneo/issues/14
